# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exemplo.mp3"
Content-Type: audio/mpeg

< ./exemplo.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/8c43814b-8a24-4462-8fec-cb2f120b2dca/transcription
Content-Type: application/json

{
  "prompt": "Chora, sofre"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "8c43814b-8a24-4462-8fec-cb2f120b2dca",
  "temperature": 0.5,
  "prompt": "Gere um resumo da transcrição do video informado a seguir: '''{transcription}'''"
}